name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.filter.outputs.changes }}
      unchanged: ${{ steps.unchanged.outputs.unchanged }}

    steps:
      # TODO: Remove, not necessary for PR
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: .github/workspaces.yml

      - name: Write filter outputs to file
        id: filter-file
        run: echo '${{ toJson(steps.filter.outputs) }}' > filter.json

      - name: Set unchanged output
        id: unchanged
        run: echo "unchanged=$(jq '[ to_entries | .[] | select(.value == "false") | .key ]' filter.json -c)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    needs: diff

    strategy:
      fail-fast: true
      matrix:
        workspace: ['@workspace/a', '@workspace/b', '@workspace/c', '@workspace/d']

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
          node-version: '18'

      - name: Early exit
        if: ${{ !contains(fromJson(needs.diff.outputs.changed), matrix.workspace) }}
        run: echo "No test required"

      - name: Install
        run: npm install

      # TODO: Lint could go here to save double install
      # - name: Lint
      #   run: npm run lint --workspace=${{ matrix.workspace }} --if-present

      - name: Test
        run: npm run test --workspace=${{ matrix.workspace }} --if-present

  no-test:
    runs-on: ubuntu-latest

    needs: diff

    strategy:
      matrix:
        workspace: ${{ fromJson(needs.diff.outputs.unchanged) }}

    steps:
      - run: echo "No test required"
