name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        # Include the workspace name here if you want to run this job
        workspace: ['@workspace/a', '@workspace/b', '@workspace/d']

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          # Include all active workspaces in this file
          filters: .github/workspaces.yml

      # Set a flag if any files in the workspace have changed
      - name: Set WORKSPACE_CHANGED environment variable
        run: echo "WORKSPACE_CHANGED=${{ contains(fromJson(steps.filter.outputs.changes), matrix.workspace) }}" >> $GITHUB_ENV

      # Use the flag to prevent running any steps unnecessarily
      - name: Setup Node
        if: env.WORKSPACE_CHANGED == 'true'
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
          node-version: '18'

      - name: Install
        if: env.WORKSPACE_CHANGED == 'true'
        run: npm install

      - name: Lint
        if: env.WORKSPACE_CHANGED == 'true'
        run: npm run lint --workspace=${{ matrix.workspace }} --if-present

      - name: Test
        if: env.WORKSPACE_CHANGED == 'true'
        run: npm run test --workspace=${{ matrix.workspace }} --if-present
