name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: .github/workspaces.yml

      - name: Set changes output
        run: echo "changes=${{ steps.filter.outputs.changes }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    needs: diff

    strategy:
      fail-fast: true
      matrix:
        workspace: ${{ fromJson(needs.diff.outputs.changes) }}

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Test
        run: yarn workspace ${{ matrix.workspace }} test
