name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  filters:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.diff.outputs.changes }}

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: diff
        with:
          filters: .github/workspaces.yml

      - name: Set changes output
        run: echo "changes=${{ steps.diff.outputs }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    needs: filters

    # strategy:
    #   fail-fast: true
    #   matrix:
    #     workspace: ${{ toJson(needs.filters.outputs.changes) }}

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Echo outputs
        run: echo ${{ toJson(needs.filters.outputs.changes) }}

      # - name: Setup Node
      #   uses: actions/setup-node@v3.5.1
      #   with:
      #     cache: 'yarn'
      #     node-version: '18'

      # - name: Install
      #   run: yarn install

      # - name: Test
      #   # if: fromJson(steps.diff.outputs.${{ matrix.workspace }}) == true
      #   run: yarn workspace ${{ matrix.workspace }} test
