name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  filters:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        workspace: ['@workspace/a', '@workspace/b', '@workspace/c']

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: diff
        with:
          filters: .github/workspaces.yml

      # - name: Early exit
      #   if: fromJson(steps.diff.outputs.${{ matrix.workspace }}) == false
      #   run: exit 0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Test
        if: fromJson(steps.diff.outputs.${{ matrix.workspace }}) == true
        run: yarn workspace ${{ matrix.workspace }} test
