name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  filters:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        workspace: ['@workspace/a', '@workspace/b', '@workspace/c']

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: diff
        with:
          filters: .github/workspaces.yml

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Echo
        run: echo ${{ steps.diff.outputs.changes }}

      - name: Echo
        run: echo ${{ fromJson(steps.diff.outputs.changes) }}

      - name: Test
        run: yarn workspace ${{ matrix.workspace }} test
        if: contains(fromJson(steps.diff.outputs.changes), ${{ matrix.workspace }})
