name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        workspace: ['@workspace/a', '@workspace/b', '@workspace/c', '@workspace/d']

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: .github/workspaces.yml

      - name: Set WORKSPACE_CHANGED environment variable
        run: echo "WORKSPACE_CHANGED=${{ contains(fromJson(steps.filter.outputs.changed), matrix.workspace) }}" >> $GITHUB_ENV

      - name: Early exit
        if: env.WORKSPACE_CHANGED == false
        run: echo "No test required"

      - name: Setup Node
        if: env.WORKSPACE_CHANGED == true
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
          node-version: '18'

      - name: Install
        if: env.WORKSPACE_CHANGED == true
        run: npm install

      # TODO: Lint could go here to save double install
      # - name: Lint
      #   run: npm run lint --workspace=${{ matrix.workspace }} --if-present

      - name: Test
        if: env.WORKSPACE_CHANGED == true
        run: npm run test --workspace=${{ matrix.workspace }} --if-present
