name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: .github/workspaces.yml

  test:
    runs-on: ubuntu-latest

    needs: diff

    strategy:
      fail-fast: true
      matrix:
        # TODO: Problem with this is required status checks!!
        # So fallback is full workspace matrix (can it still be dynamic!?)
        # And then early exit OR just if on test job
        workspace: ${{ fromJson(needs.diff.outputs.changes) }}

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      # TODO: Lint could go here to save double install
      # - name: Lint
      #   run: yarn workspace ${{ matrix.workspace }} lint

      - name: Test
        run: yarn workspace ${{ matrix.workspace }} test
