name: Filters workflow

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  filters:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        directory: [a, b, c]
        # workspace: ['@workspace/a', '@workspace/b', '@workspace/c']

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: dorny/paths-filter@v2.11.1
        id: diff
        with:
          # filters: .github/workspaces.yml
          filters: |
            changed:
              - '${{matrix.directory}}/**'

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Echo changed
        run: echo ${{ steps.diff.outputs.changed }}
        if: steps.diff.outputs.changed

      # - name: Test
      #   run: yarn workspace ${{ matrix.workspace }} test
      #   if: steps.diff.outputs.changed
