name: Parallel workflow

on:
  workflow_dispatch:

jobs:
  parallel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        workspace: [a, b, c]

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Test
        run: yarn workspace ${{ matrix.workspace }} test

  series:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test
